"""Removed year, shortname columns for resource, added semester instead

Revision ID: 0ec5c83f6511
Revises: 2fd6cb28097e
Create Date: 2024-05-08 15:51:56.511836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec5c83f6511'
down_revision: Union[str, None] = '2fd6cb28097e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('semester', sa.Integer(), nullable=True))
    op.drop_column('resource', 'year')
    op.drop_column('resource', 'shortname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('shortname', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('resource', 'semester')
    op.drop_column('resource', 'number')
    # ### end Alembic commands ###
