"""empty message

Revision ID: 73dae9a47e58
Revises: 
Create Date: 2024-02-04 14:07:12.379918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dae9a47e58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asked_course', 'user', ['user_id'], ['id'])
    op.alter_column('course', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'course', 'user', ['user_id'], ['id'])
    op.add_column('course_registered_user', sa.Column('user_level', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_registered_user', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'mentor', 'user', ['student_id'], ['id'])
    op.create_foreign_key(None, 'mentor', 'user', ['mentor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentor', type_='foreignkey')
    op.drop_constraint(None, 'mentor', type_='foreignkey')
    op.drop_constraint(None, 'course_registered_user', type_='foreignkey')
    op.drop_column('course_registered_user', 'user_level')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.alter_column('course', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'asked_course', type_='foreignkey')
    # ### end Alembic commands ###
