"""Ajout colonne description

Revision ID: 95d8413fb55d
Revises: f5b1a7f82d94
Create Date: 2024-03-02 23:20:08.616413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d8413fb55d'
down_revision: Union[str, None] = 'f5b1a7f82d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_registered_user', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_registered_user', 'description')
    # ### end Alembic commands ###
