"""Added UserNote table

Revision ID: 9d554bc90adf
Revises: beefa64eedab
Create Date: 2024-05-22 19:26:55.691460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d554bc90adf'
down_revision: Union[str, None] = 'beefa64eedab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_note', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.add_column('user_note', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_note', 'user', ['mentor_id'], ['id'])
    op.create_foreign_key(None, 'user_note', 'resource', ['resource_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_note', type_='foreignkey')
    op.drop_constraint(None, 'user_note', type_='foreignkey')
    op.drop_column('user_note', 'mentor_id')
    op.drop_column('user_note', 'resource_id')
    # ### end Alembic commands ###
