"""Added status column to course

Revision ID: beefa64eedab
Revises: 2a9abd3c5415
Create Date: 2024-05-12 18:38:21.267828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beefa64eedab'
down_revision: Union[str, None] = '2a9abd3c5415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'status')
    # ### end Alembic commands ###
