name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  run_example_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: print out example job
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          echo ${{secrets.HOSTNAME}}
